### ISSUE TITLE
Remove random.seed from templates?

### ISSUE THREAD

**Issue by ynadji** [zeek/package-template#10]
Given Zeek's deterministic option:

```
$ zeek --help 2>&1 | grep -- -D
    -D|--deterministic              | initialize random seeds to zero
```

Does it make sense to remove the `random.seed` file from the templates and use `-D` instead? How can the option be passed automatically? It wasn't clear to me how the `RANDOM_SEED` var is used.

**Comment by ckreibich** [comment]
Nice one, Yacin... the reason we use random.seed in Zeek's testsuite is that by setting `ZEEK_SEED_FILE` btest.cfg we can fix it once for all tests, unless they unset the variable. That's a bit cleaner than invoking `zeek -D` everywhere, or aliasing the invocation. But it's a great question for the template, and much of this is simply historic.

I'm not aware of a way to default-set `-D` (which'd be in the script layer, presumably). Flags and their script-layer correspondence are a bit of an inconsistent area — for example, we have `-C` to ignore checksums, and there's `ignore_checksums` in the script layer, but running with `-C` doesn't set `ignore_checksums`.

Fwiw ... I'm tempted to revamp the template's approach to testing quite a bit. The pattern so far is that people don't go back to editing the auto-created tests at all, so they're cruft from the get-go. I'm tempted to remove the default tests completely and make them a feature instead. You'd have to ask for tests to be in the resulting package specifically, and we could make the testing setup a lot more configurable. (There are certain scenarios settings where default test make a lot of sense, like when a test verifies that a plugin builds & loads — I wouldn't change that.)

So given all this ... does it still bug you? I'd leave it in there for now, and revisit this with that feature revamp.

**Comment by ynadji** [comment]
Credit is due to @JustinAzoff for letting me know about `-D`. Came up in code review.

It doesn't bother me much but I was a bit curious how easy it would be to change it, i.e., add default Zeek flags to _all_ tests that invoke Zeek. But given the flexibility of `btest` I can see that might not always be the case and would probably be clunky to implement.

Agreed on removing the default tests, but make them a feature instead. If I may, a common class of test case for me is "make test X that runs X.pcap and diffs against log Y". Being able to generate that skeleton would be nice, however, I usually find the pcaps as I'm writing the package so it would be nifty to have `zkg template` work on an _existing_ repo to generate the full test when I have the pcap(s) in hand. I'm typically copying/pasting/editing or `cat test1 | sed ... > test2` once I have the pcaps and a hand-written test anyway, so this would be a nice convenience.

I'll close this guy for now. Thanks @ckreibich !
