### ISSUE TITLE
RFC: Remove spicy:: prefix from .evt files

### ISSUE THREAD

**Issue by awelzel** [zeek/package-template#11]
IIUC, the `spicy::` prefix causes the analyzer tag to be prefixed with `SPICY_` which in turn ends up in the conn.log service field as `spicy_<analyzer>`. This causes the "tech" used to write an analyzer to leak through into the logs.

Should we remove the `spicy::` prefix from the template?

https://github.com/zeek/package-template/blob/cd045d029d3425f7848ee8d7659480758379d10e/features/spicy-protocol-analyzer/analyzer/%40ANALYZER_LOWER%40.evt%40ALT-one-unit%40#L9

Reference zeek/zeek#2651

**Comment by rsmmr** [comment]
Yeah, I can see removing this now. Originally it was meant to help identify when a Spicy analyzer is in use (as opposed to a traditional one), but seems that's less important these days, and it is kind of odd from a user's perspective to have that in there.
