### ISSUE TITLE
Include path issue for BiFs

### ISSUE THREAD

**Issue by J-Gras** [zeek/package-template#16]
For the plugin feature, including a header from the plugin sources doesn't work in BiF files:
```
module SomePlugin;

%%{
#include "MyPluginHeader.h"
%%}
```
@awelzel found this to be an include path issue: BiFs seems to be looking at `src` while the sources are in `plugin/src`.

**Comment by ckreibich** [comment]
Yeah, I can confirm — thanks for flagging. I'm taking a look.
