### ISSUE TITLE
We need CI

### ISSUE THREAD

**Issue by ckreibich** [zeek/package-template#4]
The package template needs CI coverage — the combination of features, flags, moving Zeek versions etc is too fragile to assume it just works. @rsmmr got bitten by this recently, and I once nearly pushed a breaking change to master because I didn't try out an offending combination of settings.

This relates to zeek/action-zkg-install#5: we should verify that the CI feature actually runs successfully.

**Comment by rsmmr** [comment]
Yeah, in my branch for more Spicy features I'm using a shell-script as a manual, poor-man's-CI substiute for now: https://github.com/zeek/package-template/blob/31668ba6af3af6b63c360d4a5a5b83e9530d33c7/test-spicy-features
